### ISSUE TITLE
[RFC] VREP Virtualbox VM With Jupyter notebook

### ISSUE THREAD

**Issue by psychemedia** [Troxid/vrep-api-python#4]
I've started exploring how we might be able to make use of V-REP to support a distance education course in which students would need to run V-REP on their own computers, outside of the control of the institution running the course.

One strategy we have started to explore around distributing software to distance education students is to bundle the software in a virtual machine.

To this end, I had a look at packaging a VirtualBox virtual machine containing:

1. a Linux desktop;
2. V-REP;
3. a Jupyter notebook server;
4. `vrep-api-python` package pre-installed in the Python kernel used by the Jupyter notebook.

The idea is that students can access the Jupyter notebook server running in the VM through their own browser running on the host, and then use scripts within the notebook to control the simulator running in the VM. (The simulator port can also be exposed to host.)

My first attempt can be found here: https://github.com/psychemedia/ou-robotics-vrep

I'll share notebooks via that repo, as well as scenes, as and when I get a chance to sketch them out.

The VM is built using `vagrant` (in use, we would distribute just the user `Vagrantfile` and a pre-built box).

**Comment by Troxid** [comment]
Hello @psychemedia. 
> I had a quick go at trying to write a Python class for the Line Follower robot, but I couldn't work out how to get it to move.

Can you explain what problem do you have?
You can move robot by joints (motor) ([doc](http://www.coppeliarobotics.com/helpFiles/en/jointDescription.htm), [api](https://github.com/Troxid/vrep-api-python/blob/master/pyrep/joints.py#L48)). Example with Pioneer robot already have joints. 

RGB Sensor, which very often be using on line-follower robots, can be emulate by VisionSensor (camera) ([doc](http://www.coppeliarobotics.com/helpFiles/en/visionSensors.htm), [api](https://github.com/Troxid/vrep-api-python/blob/master/pyrep/sensors.py#L24), [example](https://github.com/Troxid/vrep-api-python/blob/master/examples/testallcomponent.py#L21)). RGB Sensor is camera with 1 / 1 resolution. Or you can use vision sensor with more resolution and get average number of all pixels.

V-Rep have example (File -> Open scene -> v-rep's folder -> scenes -> lineTracer.ttt) with line-follower robot, but used internal lua scripting engine. You can remove this script (Right Mouse Button on robot in hierarchy window -> Edit -> Remove -> Associated child script) and control robots from python. Also v-rep doc have [tutorial](http://www.coppeliarobotics.com/helpFiles/en/lineFollowingBubbleRobTutorial.htm) with building line-follower robot.

> One strategy we have started to explore around distributing software to distance education students is to bundle the software in a virtual machine.

I had similar experience. That decision have pros and cons. As alternative, you can look at [Anaconda](https://www.anaconda.com/distribution/). It's easy-to-install distribution with python interpreter with many scientific libraries. But one problem: i don't tested `vrep-api-python` on windows and i don't know will be work on windows or not. In theory, working in VM with linux will be more predictable and stable with pre-configurated environment.

**Comment by psychemedia** [comment]
re: the Line Follower  - I fixed it... 

Model of the following form and then I just deleted the child script on the model, leaving the Main script in place:

```
class lineFollower:

    def __init__(self, api: VRep):
        self._api = api
        self._left_motor = api.joint.with_velocity_control("DynamicLeftJoint")
        self._right_motor = api.joint.with_velocity_control("DynamicRightJoint")
        self._left_sensor = api.sensor.vision("LeftSensor")
        self._right_sensor = api.sensor.vision("RightSensor")

    def fwd_right(self, speed=2.0):
        self._set_two_motor(speed, speed/2)

    def fwd_left(self, speed=2.0):
        self._set_two_motor(speed/2, speed)

    def move_forward(self, speed=2.0):
        self._set_two_motor(speed, speed)

    def move_backward(self, speed=2.0):
        self._set_two_motor(-speed, -speed)

    def _set_two_motor(self, left: float, right: float):
        self._left_motor.set_target_velocity(left)
        self._right_motor.set_target_velocity(right)
    
    def right_line(self):
        return self._left_sensor.read()[0]
    
    def left_line(self):
        return self._left_sensor.read()[0]
```

**Comment by Troxid** [comment]
@psychemedia  I added example with line-follower pioneer. You can detect line by vision sensor. Vision sensor return image, which represent as list of ints. In example, i calculate average of pixels, but you can implement more complex algorithm.

**Comment by psychemedia** [comment]
@Troxid Thanks. As I build my own models and example scripts I'll make sure to post them somewhere.
